repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: make format
        language: python

      - id: ruff-lint
        name: ruff-lint
        entry: make lint
        language: python