[tool.poetry]
name = "poetry install"
version = "0.1.0"
description = ""
authors = ["valer <valeria.rusy@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
